### ISSUE TITLE
Use object label as key instead of object name

### ISSUE THREAD

**Issue by artlbv** [cms-l1-dpg/Phase2-L1MenuTools#10]
Use of e.g. `tkIsoPhoton` instead of `tkPhoton` as key in plotting config allows to have several "curves" of the same object compared in the same plot. Now this is not possible as the object name `tkPhoton` is used in the key.

**Comment by artlbv** [comment]
@danielhundhausen suggested extending this with an "interface" class between the config and plotter (TBC).

**Comment by bonanomi** [comment]
@artlbv Closing this issue. Solved in https://github.com/cms-l1-dpg/Phase2-L1MenuTools/pull/16.
