### ISSUE TITLE
Update/integrade rate tool

### ISSUE THREAD

**Issue by artlbv** [cms-l1-dpg/Phase2-L1MenuTools#11]
The old rate tool needs to be integrated into the new framework.

Details are yet to be discussed, so this issue is just a placeholder for what has to happen next.

**Comment by danielhundhausen** [comment]
I think this has already been started with the `new_rate_fwk` branch and is being continued by myself in the with the rate plots developments, correct?

**Comment by artlbv** [comment]
addressed by #64
