### ISSUE TITLE
Review scaling computation

### ISSUE THREAD

**Issue by bonanomi** [cms-l1-dpg/Phase2-L1MenuTools#25]
For some object the scaling computation still looks a bit off and I believe it can be improved. This may have an impact also on the rates derivation. For example [these scalings](https://alobanov.web.cern.ch/L1T/Phase2/menu/plots/tools/V29/scalings/JetTurnonForward.png) are not ideal and we should remove the "plateau" effect we see.

**Comment by artlbv** [comment]
I think this can be closed by this https://github.com/cms-l1-dpg/Phase2-L1MenuTools/pull/73
