### ISSUE TITLE
Filter gen particles by status in caching

### ISSUE THREAD

**Issue by artlbv** [cms-l1-dpg/Phase2-L1MenuTools#40]
It seem we do not filter the genparticles by status when we cache them. 
This creates a huge collection especially for genphotons, e.g.:
```
22M	cache/V29/V29_DYLL_M50_part_e.parquet
8.0M	cache/V29/V29_DYLL_M50_part_mu.parquet
269M	cache/V29/V29_Hgg_part_gamma.parquet
4.3M	cache/V29/V29_HHToTauTau_part_tau.parquet
6.7M	cache/V29/V29_VBFHToTauTau_part_tau.parquet
```

However, we should probably at least require `status == 1` in this step, as done in the FastPuppi ntupler:
https://github.com/p2l1pfp/FastPUPPI/blob/12_5_X/NtupleProducer/python/runPerformanceNTuple.py#L339

**Comment by artlbv** [comment]
To be checked also viz the hadronic tau fixes by @bonanomi

**Comment by bonanomi** [comment]
We do have this requirement on the final state particles (in [`_filter_fspart_branches`](https://github.com/cms-l1-dpg/Phase2-L1MenuTools/blob/main/objectPerformance/src/cache_objects.py#L166C9-L166C32)). This is the collection that is used to compute the isolation wrt the gen-level particles. We can introduce this mask also in [`_filter_genpart_branches`](https://github.com/cms-l1-dpg/Phase2-L1MenuTools/blob/main/objectPerformance/src/cache_objects.py#L154C9-L154C33). Although this was not done in the C++ version of the tools. We'd need to check that introducing this requirement does not change the performance (ie a full run of validation would be required if this change is introduced)

**Comment by bonanomi** [comment]
> To be checked also viz the hadronic tau fixes by @bonanomi

For hadronic taus this additional filtering should not be required, as in that case we ask for `status==2` directly (ie I am not sure it would make sense to require `status == 1 AND status == 2`).

**Comment by artlbv** [comment]
Obsolete due to move to nano
