### ISSUE TITLE
Wildcards in config argument

### ISSUE THREAD

**Issue by danielhundhausen** [cms-l1-dpg/Phase2-L1MenuTools#47]
I think it would be nice to be able to pass wildcards (`*`) in the config command line argument. This would enable the user to produce e.g. all electron related plots with only one command:

```
python src/plotter.py cfg_plots/V29/electron*
```

Or if technically possible even all versions of all electron plots:

```
python src/plotter.py cfg_plots/V*/electron*
```

**Comment by artlbv** [comment]
I used a bash script for now `for f in ls *.yaml; do python .. $f; done`, but of course built-in functionality would be good ;)
