### ISSUE TITLE
Scaling with multiple thresholds

### ISSUE THREAD

**Issue by artlbv** [cms-l1-dpg/Phase2-L1MenuTools#5]
Some test objects require different thresholds in the computation of the scalings. For example:

![](https://user-images.githubusercontent.com/19261234/202204043-5d75e693-2f51-4f68-8c64-66dfa3763711.png)

but now we take thresholds from the reference object (hence one single threshold for multiple objects).

**Comment by bonanomi** [comment]
Solved in https://github.com/cms-l1-dpg/Phase2-L1MenuTools/pull/16 and #14 using json dump of the plots and compare script.
