### ISSUE TITLE
Improve plotting routine

### ISSUE THREAD

**Issue by artlbv** [cms-l1-dpg/Phase2-L1MenuTools#7]
- Think of introducing the possibility of having different binning for different objects (as in https://github.com/bonanomi/Phase2-L1MenuTools/issues/9 for tracker and puppi MHT)
- Allow multiple samples per plot (e.g. for tauw, we should be able to write a single config file that gives as output a single plot with the `nnTau` efficiency for H and HH samples). This is not currently possible, as the `sample` key in the config files cannot be repeated for a given object.
- Allow multiple test objects that inherit from the same file. This is a more general issue and not only related to plotting, therefore it has been documented in #6

**Comment by bonanomi** [comment]
Points 1 and 2 can now be addressed by compare_plots.py introduced in https://github.com/bonanomi/Phase2-L1MenuTools/commit/e4e94bd8c455b8374f7fc18658bf1b8030f3ec7b. Will open a PR soon.

**Comment by bonanomi** [comment]
Closing this issue. Solved in https://github.com/cms-l1-dpg/Phase2-L1MenuTools/pull/16.
