### ISSUE TITLE
Comparison slides to old fwk

### ISSUE THREAD

**Issue by artlbv** [cms-l1-dpg/Phase2-L1MenuTools#9]
Make (finish) slides comparing the new vs old framework plots

**Comment by bonanomi** [comment]
Complete comparison of turnon curves for all the objects. To be extended including also rates. [L1PhaseII_Comparison_V22.pdf](https://github.com/cms-l1-dpg/Phase2-L1MenuTools/files/10374227/L1PhaseII_Comparison_V22.pdf)
